ruby_film/config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'registrations' }
    
    resources :links
    
    root 'films#index'
    
    get '/search' => 'films#list'
    get '/film/:id' => 'films#fiche'
    get '/user_space' => 'films#user_space'
    get '/a_voir' => 'films#a_voir'










end

ruby_film/app/models/film.rb
class Film < ActiveRecord::Base

    has_many :links
    has_many :users, :through => :links

end

ruby_film/app/models/link.rb
class Link < ActiveRecord::Base

    belongs_to :film
    belongs_to :user

end

ruby_film/app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    has_many :links
    has_many :films, :through => :links
    
end

ruby_film/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
end

ruby_film/app/controllers/films_controller.rb
class FilmsController < ApplicationController

    def index
        #prints views
        if params[:query].present?
            @search = Tmdb::Movie.find(params[:query])
        else
            @popular = Tmdb::Movie.popular
        end    
    end
    
    def new
        @film = Film.new
    end
    
    def create
        @film = Film.new(params[:film])
        if @film.save
            redirect_to @film
        else
            render "new"
        end
    end
    
    def search
        @search = Tmdb::Movie.find(params[:query])
        @film_database = current_user.films.where(:film_id => params[:id]).first
        if !@film_database.nil?
          @link_film = Link.where(:user_id => current_user.id, :film_id => @film_database.id ).first
        end
    end
    
    def fiche
        #prints views
        @fiche = Tmdb::Movie.detail(params[:id])
        @trailer = Tmdb::Movie.trailers(params[:id])
        @film_database = current_user.films.where(:film_id => params[:id]).first
        if !@film_database.nil?
            @link_film = Link.where(:user_id => current_user.id, :film_id => @film_database.id ).first
        end
        p @link_film
    end
    
    def user_space
        @all_films = current_user.films
    end

    def a_voir
        @status = current_user.links.where(:status => 2)
        @links = Array.new
        @status.each do |film|
            @links.push[film.film_id]
        end
        @all_films = current_user.films.find(@links)
       end
end

ruby_film/app/controllers/links_controller.rb
class LinksController < ApplicationController
    
    def new
        @link = Link.new
    end
    
    def create
        @film = Film.where(:film_id => params[:film_id]).first

        if !@film
          @film = Film.create(:film_id => params[:film_id], :name => params[:name], :description => params[:description], :url => params[:url])
        end

        @link = current_user.links.where(:film_id => @film.id).first

        if @link && @link.status == true
            @link.destroy
        elsif @link && @link.status == false
            @link.update_attributes(:status => 1)
        else
            @link = current_user.links.build(:film_id => @film.id, :status => params[:status])
            @link.save
        end


        redirect_to :back

    end
    
    helper_method :create

end

ruby_film/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
    
end

ruby_film/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_film/app/helpers/films_controller_helper.rb
module FilmsControllerHelper
end

ruby_film/app/helpers/films_helper.rb
module FilmsHelper
end

ruby_film/app/helpers/links_helper.rb
module LinksHelper
end

ruby_film/app/views/films/a_voir.html.erb
<h1 class="title">Les films à voir :</h1>

<% @all_films.each do |result| %>
    <div class="content">
        <a class="links" href="/film/<%= result.film_id %>">
          <p class="film_title"><%= result.name %></p>
          <% if result.url %>
              <%= image_tag( "http://image.tmdb.org/t/p/w154" + result.url) %><br/><br/>
          <% end %>
        </a>
    </div><br/>
<% end %>

ruby_film/app/views/films/fiche.html.erb
<br />
<div class="content">
    <p class="film_title"><%= @fiche.title %></p>
    <% if @fiche.poster_path %>
        <%= image_tag( "http://image.tmdb.org/t/p/w154" + @fiche.poster_path) %>
    <% end %>


    <div id="vu">
        <% if (current_user && @link_film.nil?) || (current_user && @link_film.status == false) %>
            <%= form_tag( links_url, :method => "post" ) do %>
                <%= hidden_field_tag 'user_id', current_user.id %>
                <%= hidden_field_tag 'name', @fiche.title %>
                <%= hidden_field_tag 'film_id', @fiche.id %>
                <%= hidden_field_tag 'status', "1" %>
                <%= hidden_field_tag 'description', @fiche.overview %>
                <%= hidden_field_tag 'url', @fiche.poster_path  %>
                <%= submit_tag 'Vu', name: 'a_button' %>
            <% end %>
        <% elsif current_user && @link_film.status == true %>
            <%= form_tag( links_url, :method => "post" ) do %>
                <%= hidden_field_tag 'film_id', @fiche.id %>
                <%= hidden_field_tag 'status', "0" %>
                <%= submit_tag 'Pas vu', name: 'a_button' %>
            <% end %>
        <% end %>
    </div>

    <!--<div id="avoir">-->
        <!--<% if (current_user && @link_film.nil?) || (current_user && @link_film.status == false) %>-->
            <!--<%= form_tag( links_url, :method => "post" ) do %>-->
                <!--<%= hidden_field_tag 'user_id', current_user.id %>-->
                <!--<%= hidden_field_tag 'name', @fiche.title %>-->
                <!--<%= hidden_field_tag 'film_id', @fiche.id %>-->
                <!--<%= hidden_field_tag 'status', "1" %>-->
                <!--<%= hidden_field_tag 'description', @fiche.overview %>-->
                <!--<%= hidden_field_tag 'url', @fiche.poster_path  %>-->
                <!--<%= submit_tag 'A Voir', name: 'a_button' %>-->
            <!--<% end %>-->
        <!--<% elsif current_user && @link_film.status == true %>-->
            <!--<%= form_tag( links_url, :method => "post" ) do %>-->
                <!--<%= hidden_field_tag 'film_id', @fiche.id %>-->
                <!--<%= hidden_field_tag 'status', "0" %>-->
                <!--<%= submit_tag 'Déjà vu', name: 'a_button' %>-->
            <!--<% end %>-->
        <!--<% end %>-->
    <!--</div>-->

<% if @fiche.overview %>
    <div class="description">
      <p><%= @fiche.overview %></p>
    </div>
<% end %>

<% if @trailer %>
    <% @trailer.youtube.first(1).each do |trailer| %>
    <iframe width="100%" height="450" src="https://www.youtube.com/embed/<%= trailer.source %>" frameborder="0" allowfullscreen></iframe>
    <% end %>
<% end %>

ruby_film/app/views/films/index.html.erb
<div id="searchbar">
    <%= form_tag("/", method: "get") do %>
        <%= text_field_tag(:query, nil, :placeholder => "Entrez le nom d'un film") %>
    </br><%= button_tag("Rechercher") %>
    <% end %>
</div>

<% if params[:query].present? %>
    <h1 class="title"> Résultats :</h1>
    <% @search.each do |result| %>
        <div class="content">
            <a class="links" href="/film/<%= result.id %>">
                <p class="film_title"><%= result.title %></p>
                <% if result.poster_path %>
                    <%= image_tag( "http://image.tmdb.org/t/p/w154" + result.poster_path) %><br/><br/>
                <% end %>
            </a>
          <div id="vu">
            <% if (current_user && @link_film.nil?) || (current_user && @link_film.status == false) %>
                <%= form_tag( links_url, :method => "post" ) do %>
                    <%= hidden_field_tag 'user_id', current_user.id %>
                    <%= hidden_field_tag 'name', result.title %>
                    <%= hidden_field_tag 'film_id', result.id %>
                    <%= hidden_field_tag 'status', "1" %>
                    <%= hidden_field_tag 'description', result.overview %>
                    <%= hidden_field_tag 'url', result.poster_path  %>
                    <%= submit_tag 'Vu', name: 'a_button' %>
                <% end %>
            <% elsif current_user && @link_film.status == true %>
                <%= form_tag( links_url, :method => "post" ) do %>
                    <%= hidden_field_tag 'film_id', result.id %>
                    <%= hidden_field_tag 'status', "0" %>
                    <%= submit_tag 'Pas vu', name: 'a_button' %>
                <% end %>
            <% end %>
          </div></br>
        </div><br/>
    <% end %>
<% else %>
    <h1 class="title"> Popular : </h1>
    <% @popular.first(10).each do |result| %>
        <div class="content">
            <a class="links" href="/film/<%= result.id %>">
                <p class="film_title"><%= result.title %></p>
                <% if result.poster_path %>
                    <%= image_tag( "http://image.tmdb.org/t/p/w154" + result.poster_path) %><br/><br/>
                <% end %>
            </a>
          <div id="vu">
            <% if (current_user && @link_film.nil?) || (current_user && @link_film.status == false) %>
                <%= form_tag( links_url, :method => "post" ) do %>
                    <%= hidden_field_tag 'user_id', current_user.id %>
                    <%= hidden_field_tag 'name', result.title %>
                    <%= hidden_field_tag 'film_id', result.id %>
                    <%= hidden_field_tag 'status', "1" %>
                    <%= hidden_field_tag 'description', result.overview %>
                    <%= hidden_field_tag 'url', result.poster_path  %>
                    <%= submit_tag 'Vu', name: 'a_button' %>
                <% end %>
            <% elsif current_user && @link_film.status == true %>
                <%= form_tag( links_url, :method => "post" ) do %>
                    <%= hidden_field_tag 'film_id', result.id %>
                    <%= hidden_field_tag 'status', "0" %>
                    <%= submit_tag 'Pas vu', name: 'a_button' %>
                <% end %>
            <% end %>
          </div></br>
        </div><br/>
    <% end %>
<% end %>

ruby_film/app/views/films/list.html.erb
<h1> Results </h1>
<% @search.each do |result| %>
    <%= result.title %><br/>
    <%= result.id %><br/>
    <%= image_tag( "http://image.tmdb.org/t/p/w154" + result.poster_path) %><br/><br/>
<% end %>

ruby_film/app/views/films/user_space.html.erb
<h1 class="title">Les films vus :</h1>

<div class="content">
    <% @all_films.each do |result| %>
        <a class="links" href="/film/<%= result.film_id %>">
          <p class="film_title"><%= result.name %></p>
          <% if result.url %>
              <%= image_tag( "http://image.tmdb.org/t/p/w154" + result.url) %><br/><br/>
          <% end %>
    <% end %>
</div>

ruby_film/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyFilm</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <div id="title_name">
     <a href="/"><h1>RubyFilm</h1></a>
    </div>
    <nav>
        <% if user_signed_in? %>    
            <ul>
                <li>
                    <%= link_to current_user.name, user_space_path() %>
                    <ul>
                      <%= link_to "A Voir", a_voir_path() %>
                    </ul>
                </li>
                <li>
                    <%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %>
                </li>
            </ul>
        <% else %>
            <ul>
                <li>
                    <%= link_to "Se connecter", new_user_session_path %><br />
                </li>
                <li>
                    <%= link_to "S'enregistrer", new_user_registration_path %>
                </li>
            </ul>
        <% end %>
    </nav>
</header>


<%= yield %>

</body>
</html>